"""Offline market-mapping coverage audit.

Pure / no-network: computes which canonical markets each platform supports
by inspecting the registry's per-platform id attrs.
"""

from bookieskit.markets.registry import MarketRegistry

# Ordered list of platforms (display order in the markdown table).
PLATFORMS: list[str] = [
    "betpawa",
    "sportybet",
    "bet9ja",
    "betway",
    "msport",
    "sportpesa",
    "betika",
]

# Maps platform name -> MarketMapping attribute that holds its id.
_PLATFORM_ATTR: dict[str, str] = {
    "betpawa": "betpawa_id",
    "sportybet": "sportybet_id",
    "bet9ja": "bet9ja_key",
    "betway": "betway_id",
    "msport": "msport_id",
    "sportpesa": "sportpesa_id",
    "betika": "betika_id",
}


def coverage_matrix() -> dict[str, dict[str, bool]]:
    """Return support matrix: canonical_id -> {platform: supported_bool}.

    A platform is considered to support a market iff its id attr is not None.
    Rows are sorted by canonical_id for determinism.
    """
    reg = MarketRegistry()
    result: dict[str, dict[str, bool]] = {}
    for mapping in sorted(reg.list_markets(), key=lambda m: m.canonical_id):
        result[mapping.canonical_id] = {
            platform: getattr(mapping, attr) is not None
            for platform, attr in _PLATFORM_ATTR.items()
        }
    return result


def render_markdown(matrix: dict[str, dict[str, bool]]) -> str:
    """Render the coverage matrix as a markdown table.

    Args:
        matrix: Output of coverage_matrix().

    Returns:
        Markdown string with title, table, and generated-by note.
    """
    platforms = PLATFORMS
    header = "| canonical | " + " | ".join(platforms) + " |"
    separator = "| --- | " + " | ".join("---" for _ in platforms) + " |"

    rows: list[str] = []
    for canonical_id, support in sorted(matrix.items()):
        cells = " | ".join("✓" if support.get(p) else "—" for p in platforms)
        rows.append(f"| {canonical_id} | {cells} |")

    lines = [
        "# bookieskit — Market Coverage Matrix",
        "",
        header,
        separator,
        *rows,
        "",
        "_Generated by `python -m bookieskit.devtools coverage`._",
    ]
    return "\n".join(lines)
