"""Built-in market mappings (6 markets: 1X2, O/U, BTTS, DC, 1X2 1Up, 1X2 2Up)."""

from bookieskit.markets.types import MarketMapping, OutcomeMapping

BUILTIN_MAPPINGS: list[MarketMapping] = [
    MarketMapping(
        canonical_id="1x2_ft",
        name="1X2 - Full Time",
        betpawa_id="3743",
        sportybet_id="1",
        bet9ja_key="S_1X2",
        betway_id="[Win/Draw/Win]",
        msport_id="1",
        outcomes={
            "home": OutcomeMapping(
                canonical_name="home",
                betpawa="1",
                sportybet="Home",
                bet9ja="1",
                betway="__HOME__",
                msport="Home",
            ),
            "draw": OutcomeMapping(
                canonical_name="draw",
                betpawa="X",
                sportybet="Draw",
                bet9ja="X",
                betway="Draw",
                msport="Draw",
            ),
            "away": OutcomeMapping(
                canonical_name="away",
                betpawa="2",
                sportybet="Away",
                bet9ja="2",
                betway="__AWAY__",
                msport="Away",
            ),
        },
        parameterized=False,
    ),
    MarketMapping(
        canonical_id="over_under_ft",
        name="Over/Under - Full Time",
        betpawa_id="5000",
        sportybet_id="18",
        bet9ja_key="S_OU",
        betway_id="[Total Goals]",
        msport_id="18",
        outcomes={
            "over": OutcomeMapping(
                canonical_name="over",
                betpawa="Over",
                sportybet="Over",
                bet9ja="O",
                betway="Over",
                msport="Over",
            ),
            "under": OutcomeMapping(
                canonical_name="under",
                betpawa="Under",
                sportybet="Under",
                bet9ja="U",
                betway="Under",
                msport="Under",
            ),
        },
        parameterized=True,
    ),
    MarketMapping(
        canonical_id="btts_ft",
        name="Both Teams To Score - Full Time",
        betpawa_id="3795",
        sportybet_id="29",
        bet9ja_key="S_GGNG",
        betway_id="[Both Teams To Score]",
        msport_id="29",
        outcomes={
            "yes": OutcomeMapping(
                canonical_name="yes",
                betpawa="Yes",
                sportybet="Yes",
                bet9ja="Y",
                betway="Yes",
                msport="Yes",
            ),
            "no": OutcomeMapping(
                canonical_name="no",
                betpawa="No",
                sportybet="No",
                bet9ja="N",
                betway="No",
                msport="No",
            ),
        },
        parameterized=False,
    ),
    MarketMapping(
        canonical_id="double_chance_ft",
        name="Double Chance - Full Time",
        betpawa_id="4693",
        sportybet_id="10",
        bet9ja_key="S_DC",
        betway_id="[Double Chance]",
        msport_id="10",
        outcomes={
            "home_draw": OutcomeMapping(
                canonical_name="home_draw",
                betpawa="1X",
                sportybet="Home or Draw",
                bet9ja="1X",
                betway="__POS_1__",
                msport="1 X",
            ),
            "draw_away": OutcomeMapping(
                canonical_name="draw_away",
                betpawa="X2",
                sportybet="Draw or Away",
                bet9ja="X2",
                betway="__POS_3__",
                msport="X 2",
            ),
            "home_away": OutcomeMapping(
                canonical_name="home_away",
                betpawa="12",
                sportybet="Home or Away",
                bet9ja="12",
                betway="__POS_2__",
                msport="1 2",
            ),
        },
        parameterized=False,
    ),
    # 1X2 1Up — pays as 1X2 if your team gets to a 1-goal lead at any point.
    # Available on BetPawa / SportyBet / Bet9ja / Betway. MSport doesn't
    # expose this market.
    MarketMapping(
        canonical_id="1x2_1up_ft",
        name="1X2 1Up - Full Time",
        betpawa_id="28000810",
        sportybet_id="60200",
        bet9ja_key="S_1X21",
        betway_id="1X2 (1Up)",
        msport_id=None,
        outcomes={
            "home": OutcomeMapping(
                canonical_name="home",
                betpawa="1",
                sportybet="Home",
                bet9ja="11",
                betway="__HOME__",
                msport="",
            ),
            "draw": OutcomeMapping(
                canonical_name="draw",
                betpawa="X",
                sportybet="Draw",
                bet9ja="X1",
                betway="Draw",
                msport="",
            ),
            "away": OutcomeMapping(
                canonical_name="away",
                betpawa="2",
                sportybet="Away",
                bet9ja="21",
                betway="__AWAY__",
                msport="",
            ),
        },
        parameterized=False,
    ),
    # 1X2 2Up — pays as 1X2 if your team gets to a 2-goal lead at any point.
    # Same coverage as 1Up.
    MarketMapping(
        canonical_id="1x2_2up_ft",
        name="1X2 2Up - Full Time",
        betpawa_id=None,
        sportybet_id="60100",
        bet9ja_key="S_1X22",
        betway_id="1X2 (2Up)",
        msport_id=None,
        outcomes={
            "home": OutcomeMapping(
                canonical_name="home",
                betpawa="",
                sportybet="Home",
                bet9ja="12",
                betway="__HOME__",
                msport="",
            ),
            "draw": OutcomeMapping(
                canonical_name="draw",
                betpawa="",
                sportybet="Draw",
                bet9ja="X2",
                betway="Draw",
                msport="",
            ),
            "away": OutcomeMapping(
                canonical_name="away",
                betpawa="",
                sportybet="Away",
                bet9ja="22",
                betway="__AWAY__",
                msport="",
            ),
        },
        parameterized=False,
    ),
]
